name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Test
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        lisp:
        - clasp
        - cmucl
        - abcl
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yitzchak/archlinux-cl:latest
    steps:
    - name: Checkout nontrivial-gray-streams
      uses: actions/checkout@v4
      with:
        repository: yitzchak/nontrivial-gray-streams
        path: nontrivial-gray-streams
    - name: Checkout Incless
      uses: actions/checkout@v4
      with:
        repository: s-expressionists/Incless
        path: incless
    - name: Checkout Inravina
      uses: actions/checkout@v4
      with:
        path: inravina
    - name: Setup Lisp Environment
      run: |
        make-rc
        asdf-add
    - name: Run Shim Tests
      run: |
        lisp -i ${{ matrix.lisp }} -e "(ql:quickload :inravina-extrinsic/test)" -e "(inravina-extrinsic/test:ansi-test :exit t)"

