name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Test
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yitzchak/archlinux-cl:latest
    steps:
    - name: Setup environment
      run: |
        echo -e "(load \"/root/quicklisp/setup.lisp\")" > ~/.clasprc
    - name: Checkout trivial-stream-column
      uses: actions/checkout@v3
      with:
        repository: yitzchak/trivial-stream-column
        path: trivial-stream-column
    - name: Checkout Incless
      uses: actions/checkout@v3
      with:
        repository: s-expressionists/Incless
        path: incless
    - name: Checkout Inravina
      uses: actions/checkout@v3
      with:
        path: inravina
    - name: Setup ASDF registry
      run: |
        mkdir -p ~/.config/common-lisp/source-registry.conf.d
        asdf-add
    - name: Run Shim Tests (clasp)
      run: |
        clasp --eval "(asdf:test-system :inravina-shim)"

