name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Test
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yitzchak/archlinux-cl:latest
      env:
        XDG_CONFIG_HOME: /root/.config
        XDG_DATA_HOME: /root/.local/share
        XDG_CACHE_HOME: /root/.cache
    steps:
    - name: Setup environment
      run: |
        for RC in ~/.abclrc ~/ccl-init.lisp ~/.clasprc ~/.clisprc ~/.cmucl-init.lisp ~/.eclrc ~/.sbclrc
        do
          echo -e "(load \"/root/quicklisp/setup.lisp\")" > $RC
        done
    - name: Checkout trivial-stream-column
      uses: actions/checkout@v3
      with:
        repository: yitzchak/trivial-stream-column
        path: trivial-stream-column
    - name: Checkout Incless
      uses: actions/checkout@v3
      with:
        repository: s-expressionists/Incless
        path: incless
    - name: Checkout Inravina
      uses: actions/checkout@v3
      with:
        path: inravina
    - name: Setup ASDF registry
      run: |
        asdf-add
        sbcl --non-interactive --eval "(ql:quickload :inravina)"
    - name: Run Shim Tests (clasp)
      run: |
        clasp --eval "(asdf:test-system :inravina-shim)"

